<h1>CS 41344 - Natural Language Processing</h1>
<h2 style = 'color:yellow'>Assignment - 4: Semantic Analysis</h2>

<h3 style = 'color:lightgreen'>Assignment - 4.0 Import Libraries</h3>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import linalg as lg

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import TruncatedSVD

<h3 style = 'color:lightgreen'>Assignment - 4.1 Assignment Problems</h3>

<h4 style = 'color:green'>4.1.1 Compute the Eigen Vectors and Eigen Values of the following 3 matrices</h4>

Eigen vectors and eigen values cannot be computed if we have a non-square matrix. This is because to perform a linear transformation that stretches or flips the vector, and not change the direction, we need a square matrix.

In [2]:
def calculate_eigenvalues_and_eigenvectors(A):
    eigenvalues, eigenvectors = lg.eig(A)
    return eigenvalues, eigenvectors

In [3]:
def print_eigenvalues_and_eigenvectors(A):
    eigenvalues, eigenvectors = calculate_eigenvalues_and_eigenvectors(A)
    print("Eigenvalues:")
    print(np.real(eigenvalues))
    print("Eigenvectors:")
    print(np.real(eigenvectors))

In [4]:
A = np.array([
    [2, 0],
    [0, 5]
])
A

array([[2, 0],
       [0, 5]])

In [5]:
print_eigenvalues_and_eigenvectors(A)

Eigenvalues:
[2. 5.]
Eigenvectors:
[[1. 0.]
 [0. 1.]]


In [6]:
B = np.array([
    [4, 1, 6],
    [0, 2, 3],
    [0, 0, 9]
])
B

array([[4, 1, 6],
       [0, 2, 3],
       [0, 0, 9]])

In [7]:
print_eigenvalues_and_eigenvectors(B)

Eigenvalues:
[4. 2. 9.]
Eigenvectors:
[[ 1.         -0.4472136   0.76337004]
 [ 0.          0.89442719  0.25445668]
 [ 0.          0.          0.59373225]]


In [8]:
C = np.array([
    [1, 4, 0, 0],
    [0, 2, 0, 0],
    [5, 3, 1, 1],
    [4, 7, 2, 2]
])
C

array([[1, 4, 0, 0],
       [0, 2, 0, 0],
       [5, 3, 1, 1],
       [4, 7, 2, 2]])

In [9]:
print_eigenvalues_and_eigenvectors(C)

Eigenvalues:
[0. 3. 1. 2.]
Eigenvectors:
[[ 0.          0.          0.19518001  0.10929207]
 [ 0.          0.          0.          0.02732302]
 [-0.70710678 -0.4472136   0.09759001 -0.31421469]
 [ 0.70710678 -0.89442719 -0.97590007 -0.94264406]]


In [10]:
total = 80
marks = 75
print(marks/total)

0.9375


<h4 style = 'color:green'>4.1.2 Compute the SVD (Singular Value Decomposition) (3 separate matrices U,Sigma,V) of the following matrix.</h4>

In [11]:
def calculate_svd(A):
    U, s, Vt = lg.svd(A)
    return U, s, Vt

In [12]:
A = np.array([
    [5, 7, 21, 32],
    [0, 3, 43, 24],
    [2, 36, 95, 84],
    [92, 37, 57, 64]
])
A

array([[ 5,  7, 21, 32],
       [ 0,  3, 43, 24],
       [ 2, 36, 95, 84],
       [92, 37, 57, 64]])

In [13]:
U, s, Vt = calculate_svd(A)
print(f"U:\n{U}")
print(f"s:\n{s}")
print(f"Vt:\n{Vt}")

U:
[[-0.20468979 -0.10450951 -0.51344003 -0.82677638]
 [-0.24019891 -0.2628848   0.8325511  -0.42432856]
 [-0.68596945 -0.59544671 -0.19825567  0.36821708]
 [-0.65563137  0.7519392   0.06271115  0.02832426]]
s:
[181.08950358  73.81513152  14.85458672   8.32221756]
Vt:
[[-0.34631203 -0.28221783 -0.64700119 -0.61790819]
 [ 0.91397203  0.06591396 -0.36856466 -0.15643072]
 [ 0.18887868 -0.39808031  0.65688152 -0.61185258]
 [-0.09512076  0.87036804  0.11855891 -0.46835383]]


In [14]:
# Recreate the original matrix
A_reconstructed = U @ np.diag(s) @ Vt
print(f"A_reconstructed:\n{A_reconstructed}")

A_reconstructed:
[[ 5.00000000e+00  7.00000000e+00  2.10000000e+01  3.20000000e+01]
 [-3.55271368e-15  3.00000000e+00  4.30000000e+01  2.40000000e+01]
 [ 2.00000000e+00  3.60000000e+01  9.50000000e+01  8.40000000e+01]
 [ 9.20000000e+01  3.70000000e+01  5.70000000e+01  6.40000000e+01]]


In [15]:
print(f"Original matrix:\n{A}")

Original matrix:
[[ 5  7 21 32]
 [ 0  3 43 24]
 [ 2 36 95 84]
 [92 37 57 64]]


<h4 style = 'color:green'>4.1.3 Compute the SVD of this new matrix</h4>

The last two rows of the sigma matrix are zero because the last two rows of A are linearly dependent.

In [16]:
# Make the firt row of A = Sum of second and third row of A
A[0] = A[1] + A[2]
# Make the last row of A = Same as the second row of A
A[-1] = A[1]
A

array([[  2,  39, 138, 108],
       [  0,   3,  43,  24],
       [  2,  36,  95,  84],
       [  0,   3,  43,  24]])

In [17]:
U, s, Vt = calculate_svd(A)
print(f"U:\n{U}")
print(f"s:\n{s}")
print(f"Vt:\n{Vt}")

U:
[[-0.77161256 -0.06792686  0.62577601 -0.09167545]
 [-0.20657449 -0.59776833 -0.41538427 -0.65380112]
 [-0.56503807  0.52984147 -0.62577601  0.09167545]
 [-0.20657449 -0.59776833 -0.21039173  0.74547657]]
s:
[2.32669952e+02 1.86197104e+01 1.26987275e-15 7.65382685e-17]
Vt:
[[-0.01148967 -0.22209016 -0.76471652 -0.60477483]
 [ 0.04961566  0.68951315 -0.56107449  0.45530794]
 [ 0.21552967  0.66423277  0.31295486 -0.64373989]
 [-0.97516831  0.18450585  0.04963176 -0.1119868 ]]


<h4 style = 'color:green'>4.1.4 Compute the SVD of a rectangular matrix</h4>

In [18]:
def calculate_svd_rectangular(A):
    U, s, Vt = lg.svd(A, full_matrices=False)
    return U, s, Vt

In [19]:
A = np.array([
    [3, 1, 1],
    [-1, 3, 1]
])
A

array([[ 3,  1,  1],
       [-1,  3,  1]])

In [20]:
U, s, Vt = calculate_svd_rectangular(A)
print(f"U:\n{U}")
print(f"s:\n{s}")
print(f"Vt:\n{Vt}")

U:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
s:
[3.46410162 3.16227766]
Vt:
[[ 4.08248290e-01  8.16496581e-01  4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  8.32667268e-16]]


In [21]:
# Recreate the original matrix
A_reconstructed = U @ np.diag(s) @ Vt
print(f"A_reconstructed:\n{A_reconstructed}")

A_reconstructed:
[[ 3.  1.  1.]
 [-1.  3.  1.]]


In [22]:
B = np.array([
    [1, 1],
    [0, 1],
    [-1, 1]
])
B

array([[ 1,  1],
       [ 0,  1],
       [-1,  1]])

In [23]:
U, s, Vt = calculate_svd_rectangular(B)
print(f"U:\n{U}")
print(f"s:\n{s}")
print(f"Vt:\n{Vt}")

U:
[[-0.57735027 -0.70710678]
 [-0.57735027  0.        ]
 [-0.57735027  0.70710678]]
s:
[1.73205081 1.41421356]
Vt:
[[-0. -1.]
 [-1. -0.]]


In [24]:
# Recreate the original matrix
B_reconstructed = U @ np.diag(s) @ Vt
print(f"B_reconstructed:\n{B_reconstructed}")

B_reconstructed:
[[ 1.  1.]
 [ 0.  1.]
 [-1.  1.]]


<h4 style = 'color:green'>4.1.5 Using the SVD principals, perform LSA</h4>

In [25]:
def normalize_vector(v):
    return v / np.sqrt(np.sum(v**2))

In [26]:
def calculate_cosine_similarity(v1, v2):
    return np.dot(v1, v2)

In [27]:
def truncate_svd(U, S, VT, k):
    """
    Truncate the SVD matrices

    Parameters
    ----------
    U : numpy.ndarray
        U matrix from SVD decomposition
    S : numpy.ndarray
        Singular values from SVD decomposition
    VT : numpy.ndarray
        VT matrix from SVD decomposition
    k : int
        Number of singular values/columns to retain

    Returns
    -------
    truncated_U : numpy.ndarray
        Truncated U matrix
    truncated_S : numpy.ndarray
        Truncated singular values
    truncated_VT : numpy.ndarray
        Truncated VT matrix

    """
    truncated_U = U[:, :k]
    truncated_S = S[:k]
    truncated_S = np.diag(truncated_S)
    truncated_VT = VT[:k, :]
    return truncated_U, truncated_S, truncated_VT

In [28]:
def vectorize(corpus):
    """
    Convert a list of strings into a matrix of token counts
    
    Parameters
    ----------
    corpus : list
        List of strings
    """
    vectorizer = CountVectorizer()
    return vectorizer.fit_transform(corpus).toarray(), vectorizer.get_feature_names_out()

In [29]:
corpus = [
    'runs',
    'runs pitcher innings',
    'pitcher',
    'touchdown',
    'quarterback',
    'touchdown quarterback'
]
corpus

['runs',
 'runs pitcher innings',
 'pitcher',
 'touchdown',
 'quarterback',
 'touchdown quarterback']

In [30]:
bagofwords, feature_names = vectorize(corpus)
bagofwords

array([[0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1]], dtype=int64)

In [32]:
document_vector = pd.DataFrame(bagofwords, columns=feature_names)
document_vector

innings  pitcher  quarterback  runs  touchdown
0        0        0            0     1          0
1        1        1            0     1          0
2        0        1            0     0          0
3        0        0            0     0          1
4        0        0            1     0          0
5        0        0            1     0          1

In [34]:
# Create vectors
A = bagofwords[0]
B = bagofwords[1]
C = bagofwords[2]
D = bagofwords[3]
E = bagofwords[4]
F = bagofwords[5]

vectors = [A, B, C, D, E, F]
vectors

[array([0, 0, 0, 1, 0], dtype=int64),
 array([1, 1, 0, 1, 0], dtype=int64),
 array([0, 1, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 1, 0, 1], dtype=int64)]

In [36]:
# Create normalized vectors
A_normalized = normalize_vector(A)
B_normalized = normalize_vector(B)
C_normalized = normalize_vector(C)
D_normalized = normalize_vector(D)
E_normalized = normalize_vector(E)
F_normalized = normalize_vector(F)

normalized_vectors = [A_normalized, B_normalized, C_normalized, D_normalized, E_normalized, F_normalized]
pd.DataFrame(normalized_vectors, columns=feature_names)

innings  pitcher  quarterback     runs  touchdown
0  0.00000  0.00000     0.000000  1.00000   0.000000
1  0.57735  0.57735     0.000000  0.57735   0.000000
2  0.00000  1.00000     0.000000  0.00000   0.000000
3  0.00000  0.00000     0.000000  0.00000   1.000000
4  0.00000  0.00000     1.000000  0.00000   0.000000
5  0.00000  0.00000     0.707107  0.00000   0.707107

In [37]:
# Calculate Cosine Similarity and Distance

# Calculate Cosine Similarity between all vectors
number_of_documents = len(corpus)
cosine_similarity_matrix = np.zeros((number_of_documents, number_of_documents))
cosine_distance_matrix = np.zeros((number_of_documents, number_of_documents))

In [38]:
for i in range(number_of_documents):
    for j in range(number_of_documents):
        cosine_similarity_matrix[i, j] = calculate_cosine_similarity(normalized_vectors[i], normalized_vectors[j])
        cosine_distance_matrix[i, j] = 1 - cosine_similarity_matrix[i, j]

In [39]:
print(f"Cosine Similarity Matrix:\n{cosine_similarity_matrix}")

Cosine Similarity Matrix:
[[1.         0.57735027 0.         0.         0.         0.        ]
 [0.57735027 1.         0.57735027 0.         0.         0.        ]
 [0.         0.57735027 1.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.70710678]
 [0.         0.         0.         0.         1.         0.70710678]
 [0.         0.         0.         0.70710678 0.70710678 1.        ]]


In [40]:
print(f"Cosine Distance Matrix:\n{cosine_distance_matrix}")

Cosine Distance Matrix:
[[ 0.00000000e+00  4.22649731e-01  1.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00]
 [ 4.22649731e-01 -2.22044605e-16  4.22649731e-01  1.00000000e+00
   1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  4.22649731e-01  0.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+00  2.92893219e-01]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
   0.00000000e+00  2.92893219e-01]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  2.92893219e-01
   2.92893219e-01  2.22044605e-16]]


In [43]:
# Create Document-Term Matrix Term Document Matrix and calculate SVD

A_word = bagofwords.T
A_document = bagofwords

print(f"Document Term Matrix:\n{A_document}")
print()
print(f"Term Document Matrix:\n{A_word}")

Document Term Matrix:
[[0 0 0 1 0]
 [1 1 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 0 1]]

Term Document Matrix:
[[0 1 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 0 1 1]
 [1 1 0 0 0 0]
 [0 0 0 1 0 1]]


In [44]:
# Calculate SVD for the word vector
U_word, S_word, VT_word = lg.svd(A_word)

print(f"U:\n{U_word}")
print()
print(f"S:\n{S_word}")
print()
print(f"VT:\n{VT_word}")

U:
[[-4.59700843e-01 -0.00000000e+00 -0.00000000e+00 -1.57009246e-16
  -8.88073834e-01]
 [-6.27963030e-01  0.00000000e+00  0.00000000e+00  7.07106781e-01
   3.25057584e-01]
 [ 0.00000000e+00 -7.07106781e-01 -7.07106781e-01  0.00000000e+00
   0.00000000e+00]
 [-6.27963030e-01  0.00000000e+00  0.00000000e+00 -7.07106781e-01
   3.25057584e-01]
 [ 0.00000000e+00 -7.07106781e-01  7.07106781e-01  0.00000000e+00
   0.00000000e+00]]

S:
[1.93185165 1.73205081 1.         1.         0.51763809]

VT:
[[-3.25057584e-01 -8.88073834e-01 -3.25057584e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00  0.00000000e+00 -4.08248290e-01
  -4.08248290e-01 -8.16496581e-01]
 [-0.00000000e+00 -0.00000000e+00  0.00000000e+00  7.07106781e-01
  -7.07106781e-01  5.55111512e-16]
 [-7.07106781e-01  0.00000000e+00  7.07106781e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.27963030e-01 -4.59700843e-01  6.27963030e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00]


In [45]:
sigma_significant_num = 2
truncated_U, truncated_sigma, truncated_VT = truncate_svd(U_word, S_word, VT_word, sigma_significant_num)
reduced_word_vector = np.dot(truncated_U, truncated_sigma)
print(f"Reduced Word Vector:\n{reduced_word_vector}")

Reduced Word Vector:
[[-0.88807383  0.        ]
 [-1.21313142  0.        ]
 [ 0.         -1.22474487]
 [-1.21313142  0.        ]
 [ 0.         -1.22474487]]


In [46]:
# Calculate SVD for the document vector
U_document, S_document, VT_document = lg.svd(A_document)

print(f"U:\n{U_document}")
print()
print(f"S:\n{S_document}")
print()
print(f"VT:\n{VT_document}")

U:
[[-3.25057584e-01  0.00000000e+00  0.00000000e+00 -7.07106781e-01
   6.27963030e-01  0.00000000e+00]
 [-8.88073834e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -4.59700843e-01  0.00000000e+00]
 [-3.25057584e-01  0.00000000e+00  0.00000000e+00  7.07106781e-01
   6.27963030e-01  0.00000000e+00]
 [ 0.00000000e+00  4.08248290e-01 -7.07106781e-01  0.00000000e+00
   0.00000000e+00 -5.77350269e-01]
 [ 0.00000000e+00  4.08248290e-01  7.07106781e-01  0.00000000e+00
   0.00000000e+00 -5.77350269e-01]
 [ 0.00000000e+00  8.16496581e-01 -3.33066907e-16  0.00000000e+00
   0.00000000e+00  5.77350269e-01]]

S:
[1.93185165 1.73205081 1.         1.         0.51763809]

VT:
[[-0.45970084 -0.62796303  0.         -0.62796303 -0.        ]
 [-0.         -0.          0.70710678  0.          0.70710678]
 [-0.         -0.          0.70710678  0.         -0.70710678]
 [ 0.          0.70710678  0.         -0.70710678  0.        ]
 [-0.88807383  0.32505758  0.          0.32505758 -0.        ]]


In [47]:
sigma_significant_num = 2
truncated_U, truncated_sigma, truncated_VT = truncate_svd(U_document, S_document, VT_document, sigma_significant_num)
reduced_document_vector = np.dot(truncated_U, truncated_sigma)
print(f"Reduced Document Vector:\n{reduced_document_vector}")

Reduced Document Vector:
[[-0.62796303  0.        ]
 [-1.7156269   0.        ]
 [-0.62796303  0.        ]
 [ 0.          0.70710678]
 [ 0.          0.70710678]
 [ 0.          1.41421356]]


In [48]:
# Create vectors

A = reduced_document_vector[0]
B = reduced_document_vector[1]
C = reduced_document_vector[2]
D = reduced_document_vector[3]
E = reduced_document_vector[4]
F = reduced_document_vector[5]

vectors = [A, B, C, D, E, F]
vectors

[array([-0.62796303,  0.        ]),
 array([-1.7156269,  0.       ]),
 array([-0.62796303,  0.        ]),
 array([0.        , 0.70710678]),
 array([0.        , 0.70710678]),
 array([0.        , 1.41421356])]

In [49]:
# Create Normalized Vectors

A_normalized = normalize_vector(A)
B_normalized = normalize_vector(B)
C_normalized = normalize_vector(C)
D_normalized = normalize_vector(D)
E_normalized = normalize_vector(E)
F_normalized = normalize_vector(F)

normalized_vectors = [A_normalized, B_normalized, C_normalized, D_normalized, E_normalized, F_normalized]
normalized_vectors

[array([-1.,  0.]),
 array([-1.,  0.]),
 array([-1.,  0.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.])]

In [50]:
# Let's calculate the cosine similarity between the documents using the reduced matrix
number_of_documents = len(corpus)
cosine_similarity_matrix = np.zeros((number_of_documents, number_of_documents))
cosine_distance_matrix = np.zeros((number_of_documents, number_of_documents))

for i in range(number_of_documents):
    for j in range(number_of_documents):
        cosine_similarity_matrix[i, j] = calculate_cosine_similarity(normalized_vectors[i], normalized_vectors[j])
        cosine_distance_matrix[i, j] = 1 - cosine_similarity_matrix[i, j]

print(f"Cosine Similarity Matrix:\n{cosine_similarity_matrix}")
print()
print(f"Cosine Distance Matrix:\n{cosine_distance_matrix}")

Cosine Similarity Matrix:
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]

Cosine Distance Matrix:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [52]:
# Using Scikit-learn to perform LSA

sigma_significant_num = 2
svd = TruncatedSVD(n_components=sigma_significant_num)
lsa = svd.fit_transform(bagofwords)

df = pd.DataFrame(np.round(lsa, 3), columns = ['Topic 1', 'Topic 2'])
df

Topic 1  Topic 2
0    0.628   -0.000
1    1.716   -0.000
2    0.628    0.000
3    0.000    0.707
4    0.000    0.707
5    0.000    1.414

In [54]:
topic_encoded_df = pd.DataFrame(np.round(lsa, 3), columns = ['Topic 1', 'Topic 2'])
topic_encoded_df['Corups'] = corpus
topic_encoded_df.set_index('Corups', inplace=True)
topic_encoded_df

Topic 1  Topic 2
Corups                                 
runs                     0.628   -0.000
runs pitcher innings     1.716   -0.000
pitcher                  0.628    0.000
touchdown                0.000    0.707
quarterback              0.000    0.707
touchdown quarterback    0.000    1.414

In [61]:
topic_encoded_df.sort_values(by=['Topic 1'], ascending=False)

Topic 1  Topic 2
Corups                                 
runs pitcher innings     1.716   -0.000
runs                     0.628   -0.000
pitcher                  0.628    0.000
touchdown                0.000    0.707
quarterback              0.000    0.707
touchdown quarterback    0.000    1.414

In [57]:
encoding_matrix = pd.DataFrame(np.round(svd.components_, 3), index=['Topic 1', 'Topic 2'], columns=feature_names).T
encoding_matrix['abs_topic_1'] = np.abs(encoding_matrix['Topic 1'])
encoding_matrix['abs_topic_2'] = np.abs(encoding_matrix['Topic 2'])
encoding_matrix.sort_values(by=['abs_topic_1'], ascending=False)

Topic 1  Topic 2  abs_topic_1  abs_topic_2
pitcher        0.628    0.000        0.628        0.000
runs           0.628   -0.000        0.628        0.000
innings        0.460   -0.000        0.460        0.000
quarterback    0.000    0.707        0.000        0.707
touchdown      0.000    0.707        0.000        0.707

In [58]:
encoding_matrix.sort_values(by=['abs_topic_2'], ascending=False)

Topic 1  Topic 2  abs_topic_1  abs_topic_2
quarterback    0.000    0.707        0.000        0.707
touchdown      0.000    0.707        0.000        0.707
innings        0.460   -0.000        0.460        0.000
pitcher        0.628    0.000        0.628        0.000
runs           0.628   -0.000        0.628        0.000

The two top words are:

<b>Topic 1</b>
<ul>
 <li>Pitcher</li>
 <li>Runs</li>
</ul>
<br>
<b>Topic 2</b>
<ul>
 <li>Touchdown</li>
 <li>Quarterback</li>
 </ul>